FROM golang:1.20-alpine

WORKDIR /app


RUN go mod init github.com/GuddyTech/microservices-application-test.git

RUN go mod tidy

RUN go mod download && go mod verify

COPY /user.go .

RUN go build user.go

EXPOSE 8080

RUN chmod +x ./user.go

CMD ["./user"]