FROM golang:1.20-alpine

WORKDIR /app


RUN go mod init github.com/TheDevOpsSchool/student-project.git

RUN go mod tidy

RUN go mod download && go mod verify

COPY /stream.go .

RUN go build stream.go

EXPOSE 8080

RUN chmod +x ./stream.go

CMD ["./stream"]