FROM golang:1.20-alpine

WORKDIR /app


RUN go mod init github.com/TheDevOpsSchool/student-project.git

RUN go mod tidy

RUN go mod download && go mod verify

COPY /share.go .

RUN go build share.go

EXPOSE 8080

RUN chmod +x ./share.go

CMD ["./share]