FROM golang:1.20-alpine

WORKDIR /app


RUN go mod init github.com/TheDevOpsSchool/student-project.git

RUN go mod tidy

RUN go mod download && go mod verify

COPY /upload.go .

RUN go build upload.go

EXPOSE 8080

RUN chmod +x ./upload.go

CMD ["./upload"]