FROM golang:1.20-alpine

WORKDIR /app


RUN go mod init github.com/TheDevOpsSchool/student-project.git

RUN go mod tidy

RUN go mod download && go mod verify

COPY /link.go .

RUN go build link.go

EXPOSE 8080

RUN chmod +x ./link.go

CMD ["./link"]